const { transform, prettyPrint } = require('camaro');

// Example data stored directly to a variable
const xmlData = `
<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection
    timeStamp="2023-11-15T11:23:42Z"
    numberMatched="3"
    numberReturned="3"
           xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:om="http://www.opengis.net/om/2.0"
        xmlns:ompr="http://inspire.ec.europa.eu/schemas/ompr/3.0"
        xmlns:omso="http://inspire.ec.europa.eu/schemas/omso/3.0"
        xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmd="http://www.isotc211.org/2005/gmd"
        xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:swe="http://www.opengis.net/swe/2.0"
        xmlns:gmlcov="http://www.opengis.net/gmlcov/1.0"
        xmlns:sam="http://www.opengis.net/sampling/2.0"
        xmlns:sams="http://www.opengis.net/samplingSpatial/2.0"
        xmlns:wml2="http://www.opengis.net/waterml/2.0"
	xmlns:target="http://xml.fmi.fi/namespace/om/atmosphericfeatures/1.1"
        xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd
        http://www.opengis.net/gmlcov/1.0 http://schemas.opengis.net/gmlcov/1.0/gmlcovAll.xsd
        http://www.opengis.net/sampling/2.0 http://schemas.opengis.net/sampling/2.0/samplingFeature.xsd
        http://www.opengis.net/samplingSpatial/2.0 http://schemas.opengis.net/samplingSpatial/2.0/spatialSamplingFeature.xsd
        http://www.opengis.net/swe/2.0 http://schemas.opengis.net/sweCommon/2.0/swe.xsd
        http://inspire.ec.europa.eu/schemas/ompr/3.0 https://inspire.ec.europa.eu/schemas/ompr/3.0/Processes.xsd
        http://inspire.ec.europa.eu/schemas/omso/3.0 https://inspire.ec.europa.eu/schemas/omso/3.0/SpecialisedObservations.xsd
        http://www.opengis.net/waterml/2.0 http://schemas.opengis.net/waterml/2.0/waterml2.xsd
        http://xml.fmi.fi/namespace/om/atmosphericfeatures/1.1 https://xml.fmi.fi/schema/om/atmosphericfeatures/1.1/atmosphericfeatures.xsd">
    <wfs:member>
        <omso:PointTimeSeriesObservation gml:id="WFS-PWFMbB6hGB5a43P6fZ8lSpzGPouJTowqYWbbpdOt.Lnl5dsPTTv3c3Trvlw9NGXk6ddNO3L2w7OuXhh08oWliy59O6pp25bU_8Ktc6TZRGNj5c61ItCnHdOmjJq4Z2XdkqaduW1P_CrXukFEJnZtunnpyc6zGLBg5aOXRry.e._lkv7.2Xl35aemHFsyxMzZh6ZefSJmbN.PDsy1qZtN.NJXdemZw1tuHxE08.mHdjy0rV0IDS24fEXhvx6Oc4Mcze25emXfQw8sO3L0y8udbVfTuyRNPLLj6ad.5rbdPPnp3Z6mXx0rGnYZza3dds_NT6Yemnfu5zhNbj1w7NPTzJ3Zt8TW59MPTTv3VPPDLWhv4Zd2TD0wtzn038suTj1y8vN_TkrTCzbdLp1vxc8vLth6ad.7m6dd8uHpoy8nTrpp25e2HZ1y8MOnk0Omnblp9MvCZodNO3La37stY1WpDA--">
            <om:phenomenonTime>
                <gml:TimePeriod  gml:id="time1-1-1">
                    <gml:beginPosition>2023-11-14T23:23:00Z</gml:beginPosition>
                    <gml:endPosition>2023-11-15T11:23:00Z</gml:endPosition>
                </gml:TimePeriod>
            </om:phenomenonTime>
            <om:resultTime>
                <gml:TimeInstant gml:id="time2-1-1">
                    <gml:timePosition>2023-11-15T11:23:00Z</gml:timePosition>
                </gml:TimeInstant>
            </om:resultTime>
            <om:procedure xlink:href="http://xml.fmi.fi/inspire/process/opendata"/>
            <om:parameter>
                <om:NamedValue>
                    <om:name xlink:href="https://inspire.ec.europa.eu/codeList/ProcessParameterValue/value/groundObservation/observationIntent"/>
                    <om:value>
			atmosphere
                    </om:value>
                </om:NamedValue>
            </om:parameter>
            <om:observedProperty  xlink:href="https://opendata.fmi.fi/meta?observableProperty=observation&amp;param=WindDirection&amp;language=eng"/>
            <om:featureOfInterest>
                <sams:SF_SpatialSamplingFeature gml:id="fi-1-1-WindDirection">
                    <sam:sampledFeature>
                        <target:LocationCollection gml:id="sampled-target-1-1-WindDirection">
                            <target:member>
                                <target:Location gml:id="obsloc-fmisid-100949-pos-WindDirection">
                                    <gml:identifier codeSpace="http://xml.fmi.fi/namespace/stationcode/fmisid">100949</gml:identifier>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/name">Turku Artukainen</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/geoid">-16000132</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/wmo">2773</gml:name>
                                    <target:representativePoint xlink:href="#point-fmisid-100949-1-1-WindDirection"/>
                                    <target:region codeSpace="http://xml.fmi.fi/namespace/location/region">Turku</target:region>
                                </target:Location>
                            </target:member>
                        </target:LocationCollection>
                    </sam:sampledFeature>
                    <sams:shape>
                        <gml:Point gml:id="point-fmisid-100949-1-1-WindDirection" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
                            <gml:name>Turku Artukainen</gml:name>
                            <gml:pos>60.45439 22.17870 </gml:pos>
                        </gml:Point>
                    </sams:shape>
                </sams:SF_SpatialSamplingFeature>
            </om:featureOfInterest>
            <om:result>
                <wml2:MeasurementTimeseries gml:id="obs-obs-1-1-WindDirection">
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:30:00Z</wml2:time>
                            <wml2:value>26.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:40:00Z</wml2:time>
                            <wml2:value>36.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:50:00Z</wml2:time>
                            <wml2:value>47.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:00:00Z</wml2:time>
                            <wml2:value>45.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:10:00Z</wml2:time>
                            <wml2:value>27.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:20:00Z</wml2:time>
                            <wml2:value>22.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:30:00Z</wml2:time>
                            <wml2:value>21.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:40:00Z</wml2:time>
                            <wml2:value>46.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:50:00Z</wml2:time>
                            <wml2:value>36.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:00:00Z</wml2:time>
                            <wml2:value>51.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:10:00Z</wml2:time>
                            <wml2:value>61.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:20:00Z</wml2:time>
                            <wml2:value>38.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:30:00Z</wml2:time>
                            <wml2:value>36.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:40:00Z</wml2:time>
                            <wml2:value>35.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:50:00Z</wml2:time>
                            <wml2:value>43.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:00:00Z</wml2:time>
                            <wml2:value>54.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:10:00Z</wml2:time>
                            <wml2:value>51.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:20:00Z</wml2:time>
                            <wml2:value>32.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:30:00Z</wml2:time>
                            <wml2:value>50.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:40:00Z</wml2:time>
                            <wml2:value>61.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:50:00Z</wml2:time>
                            <wml2:value>36.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:00:00Z</wml2:time>
                            <wml2:value>28.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:10:00Z</wml2:time>
                            <wml2:value>35.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:20:00Z</wml2:time>
                            <wml2:value>59.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:30:00Z</wml2:time>
                            <wml2:value>49.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:40:00Z</wml2:time>
                            <wml2:value>39.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:50:00Z</wml2:time>
                            <wml2:value>30.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:00:00Z</wml2:time>
                            <wml2:value>31.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:10:00Z</wml2:time>
                            <wml2:value>38.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:20:00Z</wml2:time>
                            <wml2:value>52.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:30:00Z</wml2:time>
                            <wml2:value>45.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:40:00Z</wml2:time>
                            <wml2:value>46.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:50:00Z</wml2:time>
                            <wml2:value>45.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:00:00Z</wml2:time>
                            <wml2:value>31.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:10:00Z</wml2:time>
                            <wml2:value>24.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:20:00Z</wml2:time>
                            <wml2:value>23.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:30:00Z</wml2:time>
                            <wml2:value>30.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:40:00Z</wml2:time>
                            <wml2:value>33.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:50:00Z</wml2:time>
                            <wml2:value>36.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:00:00Z</wml2:time>
                            <wml2:value>28.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:10:00Z</wml2:time>
                            <wml2:value>37.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:20:00Z</wml2:time>
                            <wml2:value>34.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:30:00Z</wml2:time>
                            <wml2:value>27.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:40:00Z</wml2:time>
                            <wml2:value>26.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:50:00Z</wml2:time>
                            <wml2:value>33.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:00:00Z</wml2:time>
                            <wml2:value>31.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:10:00Z</wml2:time>
                            <wml2:value>21.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:20:00Z</wml2:time>
                            <wml2:value>28.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:30:00Z</wml2:time>
                            <wml2:value>58.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:40:00Z</wml2:time>
                            <wml2:value>53.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:50:00Z</wml2:time>
                            <wml2:value>57.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:00:00Z</wml2:time>
                            <wml2:value>69.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:10:00Z</wml2:time>
                            <wml2:value>76.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:20:00Z</wml2:time>
                            <wml2:value>63.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:30:00Z</wml2:time>
                            <wml2:value>68.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:40:00Z</wml2:time>
                            <wml2:value>59.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:50:00Z</wml2:time>
                            <wml2:value>57.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:00:00Z</wml2:time>
                            <wml2:value>68.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:10:00Z</wml2:time>
                            <wml2:value>45.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:20:00Z</wml2:time>
                            <wml2:value>60.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:30:00Z</wml2:time>
                            <wml2:value>67.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:40:00Z</wml2:time>
                            <wml2:value>67.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:50:00Z</wml2:time>
                            <wml2:value>61.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:00:00Z</wml2:time>
                            <wml2:value>67.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:10:00Z</wml2:time>
                            <wml2:value>59.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:20:00Z</wml2:time>
                            <wml2:value>46.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:30:00Z</wml2:time>
                            <wml2:value>63.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:40:00Z</wml2:time>
                            <wml2:value>67.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:50:00Z</wml2:time>
                            <wml2:value>30.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:00:00Z</wml2:time>
                            <wml2:value>28.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:10:00Z</wml2:time>
                            <wml2:value>22.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:20:00Z</wml2:time>
                            <wml2:value>24.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                </wml2:MeasurementTimeseries>
            </om:result>
        </omso:PointTimeSeriesObservation>
    </wfs:member>
    <wfs:member>
        <omso:PointTimeSeriesObservation gml:id="WFS-7LoH05o.hECNIvARXcZHnL9_2quJTowqYWbbpdOt.Lnl5dsPTTv3c3Trvlw9NGXk6ddNO3L2w7OuXhh08oWliy59O6pp25bU_8Ktc6TZRGNj5c61ItCnHdOmjJq4Z2XdkqaduW1P_CrXukFEJnZtunnpyc6zGLBg5aOXRry.e._lkv7.2Xl35aemHFsyxMzZh6ZefSJmbN.PDsy1qZtN.NJXdemZw1tuHxE08.mHdjy0rV0IDS24fEXhvx6Oc4Mcze25emXfQw8sO3L0y8uda1fTuyU.GXLkm02tt08.endnqZfHSsadhnNrd12z81Pph6ad.7nOE1uPXDs09PMndm3xNbn0w9NO_dU88MtaG_hl3ZMPTC3OfTfyy5OPXLy839OStMLNt0unW_Fzy8u2Hpp37ubp13y4emjLydOumnbl7YdnXLww6eTQ6aduWn0y8Jmh007ctrfuy1jVakMA">
            <om:phenomenonTime xlink:href="#time1-1-1"/>
            <om:resultTime xlink:href="#time2-1-1"/>
            <om:procedure xlink:href="http://xml.fmi.fi/inspire/process/opendata"/>
            <om:parameter>
                <om:NamedValue>
                    <om:name xlink:href="https://inspire.ec.europa.eu/codeList/ProcessParameterValue/value/groundObservation/observationIntent"/>
                    <om:value>
			atmosphere
                    </om:value>
                </om:NamedValue>
            </om:parameter>
            <om:observedProperty  xlink:href="https://opendata.fmi.fi/meta?observableProperty=observation&amp;param=WindSpeedMS&amp;language=eng"/>
            <om:featureOfInterest>
                <sams:SF_SpatialSamplingFeature gml:id="fi-1-1-WindSpeedMS">
                    <sam:sampledFeature>
                        <target:LocationCollection gml:id="sampled-target-1-1-WindSpeedMS">
                            <target:member>
                                <target:Location gml:id="obsloc-fmisid-100949-pos-WindSpeedMS">
                                    <gml:identifier codeSpace="http://xml.fmi.fi/namespace/stationcode/fmisid">100949</gml:identifier>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/name">Turku Artukainen</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/geoid">-16000132</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/wmo">2773</gml:name>
                                    <target:representativePoint xlink:href="#point-fmisid-100949-1-1-WindSpeedMS"/>
                                    <target:region codeSpace="http://xml.fmi.fi/namespace/location/region">Turku</target:region>
                                </target:Location>
                            </target:member>
                        </target:LocationCollection>
                    </sam:sampledFeature>
                    <sams:shape>
                        <gml:Point gml:id="point-fmisid-100949-1-1-WindSpeedMS" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
                            <gml:name>Turku Artukainen</gml:name>
                            <gml:pos>60.45439 22.17870 </gml:pos>
                        </gml:Point>
                    </sams:shape>
                </sams:SF_SpatialSamplingFeature>
            </om:featureOfInterest>
            <om:result>
                <wml2:MeasurementTimeseries gml:id="obs-obs-1-1-WindSpeedMS">
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:30:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:40:00Z</wml2:time>
                            <wml2:value>2.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:50:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:00:00Z</wml2:time>
                            <wml2:value>2.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:10:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:20:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:30:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:40:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:50:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:00:00Z</wml2:time>
                            <wml2:value>3.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:10:00Z</wml2:time>
                            <wml2:value>3.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:20:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:30:00Z</wml2:time>
                            <wml2:value>3.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:40:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:50:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:00:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:10:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:20:00Z</wml2:time>
                            <wml2:value>2.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:30:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:40:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:50:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:00:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:10:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:20:00Z</wml2:time>
                            <wml2:value>3.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:30:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:40:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:50:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:00:00Z</wml2:time>
                            <wml2:value>3.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:10:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:20:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:30:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:40:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:50:00Z</wml2:time>
                            <wml2:value>2.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:00:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:10:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:20:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:30:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:40:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:50:00Z</wml2:time>
                            <wml2:value>2.1</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:00:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:10:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:20:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:30:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:40:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:50:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:00:00Z</wml2:time>
                            <wml2:value>2.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:10:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:20:00Z</wml2:time>
                            <wml2:value>2.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:30:00Z</wml2:time>
                            <wml2:value>2.1</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:40:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:50:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:00:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:10:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:20:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:30:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:40:00Z</wml2:time>
                            <wml2:value>3.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:50:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:00:00Z</wml2:time>
                            <wml2:value>2.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:10:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:20:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:30:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:40:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:50:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:00:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:10:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:20:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:30:00Z</wml2:time>
                            <wml2:value>2.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:40:00Z</wml2:time>
                            <wml2:value>2.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:50:00Z</wml2:time>
                            <wml2:value>2.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:00:00Z</wml2:time>
                            <wml2:value>2.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:10:00Z</wml2:time>
                            <wml2:value>2.0</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:20:00Z</wml2:time>
                            <wml2:value>2.9</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                </wml2:MeasurementTimeseries>
            </om:result>
        </omso:PointTimeSeriesObservation>
    </wfs:member>
    <wfs:member>
        <omso:PointTimeSeriesObservation gml:id="WFS-zKE9KgoSdGLSV9zt_Jj6yO9MKgmJTowqYWbbpdOt.Lnl5dsPTTv3c3Trvlw9NGXk6ddNO3L2w7OuXhh08oWliy59O6pp25bU_8Ktc6TZRGNj5c61ItCnHdOmjJq4Z2XdkqaduW1P_CrXukFEJnZtunnpyc6zGLBg5aOXRry.e._lkv7.2Xl35aemHFsyxMzZh6ZefSJmbN.PDsy1qZtN.NJXdemZw1tuHxE08.mHdjy0rV0IDS24fEXhvx6Oc4Mcze25emXfQw8sO3L0y8uda1TLt4ZeWHp15ZWtt08.endnqZfHSsadhnNrd12z81Pph6ad.7nOE1uPXDs09PMndm3xNbn0w9NO_dU88MtaG_hl3ZMPTC3OfTfyy5OPXLy839OStMLNt0unW_Fzy8u2Hpp37ubp13y4emjLydOumnbl7YdnXLww6eTQ6aduWn0y8Jmh007ctrfuy1jVakMA">
            <om:phenomenonTime xlink:href="#time1-1-1"/>
            <om:resultTime xlink:href="#time2-1-1"/>
            <om:procedure xlink:href="http://xml.fmi.fi/inspire/process/opendata"/>
            <om:parameter>
                <om:NamedValue>
                    <om:name xlink:href="https://inspire.ec.europa.eu/codeList/ProcessParameterValue/value/groundObservation/observationIntent"/>
                    <om:value>
			atmosphere
                    </om:value>
                </om:NamedValue>
            </om:parameter>
            <om:observedProperty  xlink:href="https://opendata.fmi.fi/meta?observableProperty=observation&amp;param=Temperature&amp;language=eng"/>
            <om:featureOfInterest>
                <sams:SF_SpatialSamplingFeature gml:id="fi-1-1-Temperature">
                    <sam:sampledFeature>
                        <target:LocationCollection gml:id="sampled-target-1-1-Temperature">
                            <target:member>
                                <target:Location gml:id="obsloc-fmisid-100949-pos-Temperature">
                                    <gml:identifier codeSpace="http://xml.fmi.fi/namespace/stationcode/fmisid">100949</gml:identifier>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/name">Turku Artukainen</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/geoid">-16000132</gml:name>
                                    <gml:name codeSpace="http://xml.fmi.fi/namespace/locationcode/wmo">2773</gml:name>
                                    <target:representativePoint xlink:href="#point-fmisid-100949-1-1-Temperature"/>
                                    <target:region codeSpace="http://xml.fmi.fi/namespace/location/region">Turku</target:region>
                                </target:Location>
                            </target:member>
                        </target:LocationCollection>
                    </sam:sampledFeature>
                    <sams:shape>
                        <gml:Point gml:id="point-fmisid-100949-1-1-Temperature" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
                            <gml:name>Turku Artukainen</gml:name>
                            <gml:pos>60.45439 22.17870 </gml:pos>
                        </gml:Point>
                    </sams:shape>
                </sams:SF_SpatialSamplingFeature>
            </om:featureOfInterest>
            <om:result>
                <wml2:MeasurementTimeseries gml:id="obs-obs-1-1-Temperature">
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:30:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:40:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-14T23:50:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:00:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:10:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:20:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:30:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:40:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T00:50:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:00:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:10:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:20:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:30:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:40:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T01:50:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:00:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:10:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:20:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:30:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:40:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T02:50:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:00:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:10:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:20:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:30:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:40:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T03:50:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:00:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:10:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:20:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:30:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:40:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T04:50:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:00:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:10:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:20:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:30:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:40:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T05:50:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:00:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:10:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:20:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:30:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:40:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T06:50:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:00:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:10:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:20:00Z</wml2:time>
                            <wml2:value>-0.8</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:30:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:40:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T07:50:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:00:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:10:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:20:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:30:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:40:00Z</wml2:time>
                            <wml2:value>-0.7</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T08:50:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:00:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:10:00Z</wml2:time>
                            <wml2:value>-0.6</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:20:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:30:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:40:00Z</wml2:time>
                            <wml2:value>-0.5</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T09:50:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:00:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:10:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:20:00Z</wml2:time>
                            <wml2:value>-0.4</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:30:00Z</wml2:time>
                            <wml2:value>-0.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:40:00Z</wml2:time>
                            <wml2:value>-0.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T10:50:00Z</wml2:time>
                            <wml2:value>-0.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:00:00Z</wml2:time>
                            <wml2:value>-0.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:10:00Z</wml2:time>
                            <wml2:value>-0.2</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                    <wml2:point>
                        <wml2:MeasurementTVP>
                            <wml2:time>2023-11-15T11:20:00Z</wml2:time>
                            <wml2:value>-0.3</wml2:value>
                        </wml2:MeasurementTVP>
                    </wml2:point>
                </wml2:MeasurementTimeseries>
            </om:result>
        </omso:PointTimeSeriesObservation>
    </wfs:member>
</wfs:FeatureCollection>
`
// Template is a set of conversion instructions 
const template = ['pageData/entry',
{
    time: 'timeStamp',
    price: 'number(price)',
    temperature: 'number(temperature)',
    windSpeed: 'number(windSpeed)'
}];

const xml2objectArray2 = async (xmlData, template) => {
    const result = await transform(xmlData, template);
    return result
  }

xml2objectArray2(xmlData, template).then(result => {
    dataResult = result;
    console.log(result)
});